apiVersion: 1

providers:
  - name: General Dashboards
    folder: General
    type: file
    options:
      path: /var/lib/grafana/dashboards/general

  - name: Prometheus Dashboards
    folder: Prometheus
    type: file
    options:
      path: /var/lib/grafana/dashboards/prometheus

  - name: Grafana Dashboards
    folder: Grafana
    type: file
    options:
      path: /var/lib/grafana/dashboards/grafana

  - name: cAdvisor Dashboards
    folder: cAdvisor
    type: file
    options:
      path: /var/lib/grafana/dashboards/cadvisor
