version: "3"
services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - monitoring
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - monitoring
      # - default
    volumes:
      - "prometheus-scrape-config.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=200h"
    privileged: true
    depends_on:
      - cadvisor
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "10"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - monitoring
      # - default
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "grafana-datasource-config.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      # - "./dashboards/prometheus:/var/lib/grafana/dashboards/prometheus"
      # - "./dashboards/grafana:/var/lib/grafana/dashboards/grafana"
      # - "./dashboards/cadvisor:/var/lib/grafana/dashboards/cadvisor"
      - "dashboards:/var/lib/grafana/dashboards"
      - "default.yml:/etc/grafana/provisioning/dashboards/default.yml"
    privileged: true
    depends_on:
      - prometheus
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "10"

  nginx:
    image: nginx:latest
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    ports:
      # - "9090:9090" # Exposition de Nginx pour Prometheus
      # - "3000:3000" # Exposition de Nginx pour Grafana
      - "9393:9090" # Exposition de Nginx pour Prometheus
      - "3030:3000" # Exposition de Nginx pour Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana

volumes:
  grafana-data:
  prometheus-data:
  nginx-logs:

networks:
  monitoring:
    driver: bridge
  # default:
  #   external: true
